### PR TITLE
Fixes #2057 gracefully

### LINKED ISSUE #2057: Depth service sometimes can return no value
## To reproduce
http://localhost:8080/aodn-portal/depth?lat=-9.09765625&lon=48.251953125 or
https://imos.aodn.org.au/imos123/depth?lat=-9.09765625&lon=48.251953125

## What happens
No depth value is returned
```
<root>
    <latitude>-9.09765625</latitude>
    <longitude>48.251953125</longitude>
    <depth></depth>
</root>
```
## What should happen
Always the geographically closest value is returned

### PR DESCRIPTION
**Pull request by pmbohm**

### CODE REVIEW

File: web-app/js/portal/ui/FeatureInfoPopup.js [hunk 1]
```diff
@@ -277,22 +277,20 @@ Portal.ui.FeatureInfoPopup = Ext.extend(GeoExt.Popup, {
...
-            if (xmldoc && xmldoc.getElementsByTagName('depth') !== undefined) {
-                var depth = xmldoc.getElementsByTagName('depth')[0].firstChild.nodeValue;
-                var label = OpenLayers.i18n(depth <= 0 ? 'depthLabel' : 'elevationLabel');
-
-                this.depthInfoPanel.update(this.locationString + " " + this._boldify(label) + " " + Math.abs(depth) + "m");
-            }
-            else {
-                this.depthInfoPanel.update("");
+            if (xmldoc) {
+                var depthTag = xmldoc.getElementsByTagName('depth')[0].firstChild;
```
Comment (danfruehauf) [inline web-app/js/portal/ui/FeatureInfoPopup.js]: And if there is no `depth` tag? Why did you change the original if statement?

The original is safer:
```
if (xmldoc && xmldoc.getElementsByTagName('depth') !== undefined) {
```

File: web-app/js/portal/ui/FeatureInfoPopup.js [hunk 2]
```diff
@@ -277,22 +277,20 @@ Portal.ui.FeatureInfoPopup = Ext.extend(GeoExt.Popup, {
...
+                // Depth service can return 204 but our app changes that to a 200 and pipes down nothing
+                if (depthTag != null) {
+                    var depth = depthTag.nodeValue;
+                    if (depth) {
+                        var label = OpenLayers.i18n(depth <= 0 ? 'depthLabel' : 'elevationLabel');
+                        this.depthInfoPanel.update(this.locationString + " " + this._boldify(label) + " " + Math.abs(depth) + "m");
+                        return;
```
Comment (danfruehauf) [inline web-app/js/portal/ui/FeatureInfoPopup.js]: Instead of the `return`, you can leave it as the original `if/else` statement. Especially since there's no test coverage for that code.

File: web-app/js/portal/ui/FeatureInfoPopup.js (hunk 1 above)
Comment (pmbohm) [inline web-app/js/portal/ui/FeatureInfoPopup.js]: agreed

File: web-app/js/portal/ui/FeatureInfoPopup.js (hunk 2 above)
Comment (pmbohm) [inline web-app/js/portal/ui/FeatureInfoPopup.js]: The added line `this.depthInfoPanel.update("&nbsp;");` will now be reached unless depth tag exists and is a number.
There's more `ifs` now and just one catchall

**Comment by pmbohm** [comment]
@danfruehauf new pull request now ready

File: web-app/js/portal/ui/FeatureInfoPopup.js (hunk 2 above)
Comment (danfruehauf) [inline web-app/js/portal/ui/FeatureInfoPopup.js]: How about:
```
var html = "&nbsp";

if (xml) {
   SOME_LOGIC;
   html = "NEW_DEPTH";
}

this.depthInfoPanel.update(html);
```

No more complex `if`s. There's just a default value can or cannot be updated.

**Comment by danfruehauf** [comment]
Yeah, have you seen my last comment though?

File: web-app/js/portal/ui/FeatureInfoPopup.js [hunk 3]
```diff
@@ -277,22 +277,20 @@ Portal.ui.FeatureInfoPopup = Ext.extend(GeoExt.Popup, {
...
-            else {
-                this.depthInfoPanel.update("");
+                var depthTag = xmldoc.getElementsByTagName('depth')[0].firstChild;
+                // Depth service can return 204 but our app changes that to a 200 and pipes down nothing
+                if (depthTag != null) {
+                    var depth = depthTag.nodeValue;
+                    if (depth && (+depth === +depth)) {
+                        var label = OpenLayers.i18n(depth <= 0 ? 'depthLabel' : 'elevationLabel');
+                        this.depthInfoPanel.update(this.locationString + " " + this._boldify(label) + " " + Math.abs(depth) + "m");
+                        return;
```
Comment (danfruehauf) [inline web-app/js/portal/ui/FeatureInfoPopup.js]: I'll comment again, so it's not on an outdated diff:



How about:

var html = "&nbsp";

if (xml) {
   SOME_LOGIC;
   html = "NEW_DEPTH";
}

this.depthInfoPanel.update(html);

No more complex ifs. There's just a default value can or cannot be updated.

**Comment by pmbohm** [comment]
@danfruehauf Just saw it. What is the problem with `return;` ?
Its used throughout the code.

**Comment by danfruehauf** [comment]
I'll argue it's more elegant with a default value and opportunistic modification. But up to you.

**Comment by jonescc** [comment]
I'd write it the way @danfruehauf is suggesting it too.  But there's nothing wrong with how you are doing it.
