### PR TITLE
#1870 - On reset apply the filter values from controls

### LINKED ISSUE #1870: Temporal extent on download step not updated after 'clear subset'
**Steps to reproduce:**
1. Add an ncwms collection, e.g. ACORN
2. Edit the "from date" in the subset panel (to a more recent year than the default, for example)
3. Click 'clear subset'
4. Go to step 3.

**What should happen:**
The temporal extent shown on step 3 should reflect the full extent of the collection.

**What does happen:**
The temporal extent shows what was set in point 2 in the steps to reproduce above.

Note: seems as though this bug was introduced in https://github.com/aodn/aodn-portal/commit/6d13c170cc6e746e (according to `git bisect`).

### PR DESCRIPTION
**Pull request by dnahodil**
Fixes #1870

### CODE REVIEW

File: web-app/js/portal/details/NcWmsPanel.js [hunk 1]
```diff
@@ -383,6 +383,7 @@ Portal.details.NcWmsPanel = Ext.extend(Ext.Container, {
         this._updateTimeRangeLabel();
 
         this._setLayerSubsetExtent();
+        this._applyFilterValuesFromMap();
```
Comment (jkburges) [inline web-app/js/portal/details/NcWmsPanel.js]: I think this is a bit confusing.  Really, what we want to express at this level is `_applyFilterValuesToCollection`.  This method should in turn do the bit about getting the constraint from the map (it shouldn't really be getting it from *there*, but that's a different story).

**Comment by dnahodil** [comment]
Changes made. I think I addressed your comment, if you meant that the important thing is that the filters are being applied *to the collection* and not the the filters were *coming from the map*.
