### PR TITLE
Fixes #2502

### LINKED ISSUE #2502: Some layers with diver platform have empty platform row in results
**Steps to reproduce:**

In the platform facet expand "Biological platform" and select "diver".

**What should happen:**

All results contain "Biological platform" in the platform row.

**What does happen:**

"Mapping of selected areas of Cockburn Sound, Western Australia", "Habitat Maps derived from Point Lookout Ecological Surveys (PLEA)" and "Ecophysiology of three habitat-forming seaweeds across a depth and latitudinal gradient in southeastern Australia" are missing the platform row.

### PR DESCRIPTION
**Pull request by akashisama**
Handle the case where metadata lists a non-recognized platform before any recognized platform

### CODE REVIEW

File: web-app/js/portal/search/FacetedSearchResultsDataView.js [hunk 1]
```diff
@@ -186,21 +186,25 @@ Portal.search.FacetedSearchResultsDataView = Ext.extend(Ext.DataView, {
...
-            broader = broader.filter(function(item, pos) {
-                return !pos || item != broader[pos - 1];
-            });
-            return template.apply({
-                "label": label,
-                "value": broader.join(', ')
-            });
+        var broader = [];
+        var i = 0;
+        for(i=0;i<platforms.length;i++) {
```
Comment (anguss00) [inline web-app/js/portal/search/FacetedSearchResultsDataView.js]: I reckon we can use Ext.each here instead of an iterator... saves a variable assignment

**Comment by anguss00** [comment]
Also, when I select Platform-> Biological platform -> Diver, the platform row disappears from the search results which I don't think is the required behaviour

**Comment by anguss00** [comment]
Scratch that, saw the changes at the same time as I commented!!
