### PR TITLE
Tracking GFI now clearer. fixes #2643

### LINKED ISSUE #2643: Spurious Google Analytics Event
## Steps to reproduce
Go to google analytics
Select BEHAVIOR
Select Events
Select Top Events 
Select (Event Category) DataCollections

## What happens
There's an event action named "Feature Information"

## What should happen
Depends what the event is.  Is it a download? If so it needs renaming. Is it a GFI  request? If so it should be under the "FeatureInfo" event category. Let me know what's going on with this and we can decide what to do about it.

analytics 5

### PR DESCRIPTION
**Pull request by pmbohm**

### CODE REVIEW

File: web-app/js/portal/utils/trackUsage.js [hunk 1]
```diff
@@ -6,6 +6,9 @@ function trackUsage(category, action, label, collection, value) {
             dimension1: collection
         });
     }
+    else {
+        //console.log(String.format("ga('send', 'event', category={0}, action={1}, label={2}, value={3})",category, action, label, collection, value));
```
Comment (anguss00) [inline web-app/js/portal/utils/trackUsage.js]: A wild console log appears

Comment (pmbohm) [reply web-app/js/portal/utils/trackUsage.js]: @anguss00 I am now officially sick or re-writing this line every time that there is some work regarding tracking. I imagine if this line was available to be uncommented this bug would not even have come into existence.

Comment (anguss00) [reply web-app/js/portal/utils/trackUsage.js]: Fairo
