### PR TITLE
Fixes 'Next time period' button and made time dropdown collapsable

### LINKED ISSUE #2340: Cannot move time forward on map
App version: 4.25.9 - Systest on Chrome
            Build date: Thu Sep 22 13:15:18 AEST 2016
            Build number: 73
            Git ref: fcd27bff088ce4cb22731561ed1de45c3d9c16ff

Steps to reproduce:

Add any ncWMS (i.e. ACORN) Collection, select a different time for the from date (but not the last in the drop down list). note the Displayed date and time changes to that date and time. Try to click the right facing arrows to change the display on the map

What should happen:

Diplay on map proceeds forward to next time on that from date.

What does happen:

Nothing the right facing arrows aren't active - however if you click the left then the right they do activate.

### PR DESCRIPTION
**Pull request by bhasin85**
Fixes #2340

### CODE REVIEW

File: web-app/js/portal/details/NcWmsPanel.js [hunk 1]
```diff
@@ -339,10 +339,12 @@ Portal.details.NcWmsPanel = Ext.extend(Ext.Container, {
 
     _onTimeSelected: function(datePicker, selectedDateTimeMoment) {
         datePicker.setValue(selectedDateTimeMoment);
+        datePicker.tf.collapse();
```
Comment (jonescc) [inline web-app/js/portal/details/NcWmsPanel.js]: Time dropdown doesn't collapse for me when I select a time as per problem description - or was this for something else?
