### PR TITLE
Fixes #1597.

### LINKED ISSUE #1597: If no applicable top level parameters are set should not show in results
Instance name: IMOS
            App version: 3.41.2
            Build date: Thu Feb 19 09:38:07 AEDT 2015
            Build number: 357
            Git ref: e9cec741231a49f2774f7397860b0be6cbdbb353

Steps to reproduce:

Select biological platform. Look at list of results

What should happen:

If there is no applicable parameter set then the row should not be seen

What does happen:

Parameter symbol of that which is not set show but with no text

symbol only

### PR DESCRIPTION
**Pull request by jkburges**
If a collection does not have any measured parameters, show a message indicating such, as opposed to a blank string.

### CODE REVIEW

File: src/test/javascript/portal/search/FacetedSearchResultsDataViewSpec.js [hunk 1]
```diff
@@ -114,4 +114,25 @@ describe("Portal.search.FacetedSearchResultsDataView", function() {
             expect(window.trackUsage).toHaveBeenCalledWith("Collection", "select", "Argo Australia Profiles");
         });
     });
+
+    describe('_getMeasuredParametersAsCommaSeparatedString', function() {
+
+        beforeEach(function() {
+            params = [];
```
Comment (dnahodil) [inline src/test/javascript/portal/search/FacetedSearchResultsDataViewSpec.js]: An accidental global variable. Needs 'var' keyword.

Same again, below.

File: web-app/js/portal/search/FacetedSearchResultsDataView.js [hunk 2]
```diff
@@ -132,13 +132,24 @@ Portal.search.FacetedSearchResultsDataView = Ext.extend(Ext.DataView, {
...
                 "label": label,
-                "value": this.getMeasuredParameters(values)
+                "value": this._getMeasuredParametersAsCommaSeparatedString(values)
             });
         }
         return "";
     },
 
-    getMeasuredParameters: function(values) {
+    _getMeasuredParametersAsCommaSeparatedString: function(values) {
```
Comment (dnahodil) [inline web-app/js/portal/search/FacetedSearchResultsDataView.js]: Maybe consider calling this `_getMeasuredParametersText()` or something? It's a touch shorter and we wouldn't have to change it if we changed symbols again (we used to separate with pipes '|').

**Comment by dnahodil** [comment]
Changes look good @jkburges. Just a couple of comments.

**Comment by jkburges** [comment]
Updated @dnahodil
