### PR TITLE
Removed Some parts of af08e465b224cfc6354a652fcdb660c644876cfb as they were unused. Removed listeners from DataCollectionDetailsPanel when a dataCollection is deleted.

### LINKED ISSUE #1809: Removing a collection before it has finished loading results in errors
**Steps to reproduce**
Add a collection and then remove it again before it has finished loading

**What should happen**
Collection should be removed

**What does happen**
Many JavaScript errors

### PR DESCRIPTION
**Pull request by pmbohm**
…

Fixes #1809

### CODE REVIEW

**Comment by dnahodil** [comment]
I'll check this out

File: web-app/js/portal/details/DataCollectionDetailsPanel.js [hunk 1]
```diff
@@ -14,18 +14,7 @@ Portal.details.DataCollectionDetailsPanel = Ext.extend(Ext.Panel, {
...
-        }, this);
-
-        cfg.dataCollection.getLayerState().on('loadend', function() {
-            this._onLayerLoadEnd();
-        }, this);
-
-        cfg.dataCollection.getLayerState().on('tileerror', function() {
-            this._onLayerLoadError();
-        }, this);
+        this.addListeners(cfg.dataCollection.getLayerState());
```
Comment (dnahodil) [inline web-app/js/portal/details/DataCollectionDetailsPanel.js]: It's nice how you've extracted this method out (and the new `removeListeners()` method). It makes the constructor much tidier.

File: web-app/js/portal/prototypes/OpenLayers.js [hunk 2]
```diff
@@ -232,25 +232,3 @@ OpenLayers.Geometry.prototype.crossesAntimeridian = function() {
...
-    if (this.destroyDeferred) {
-        return;
-    }
-
-    this.events.register('loadend', this, function() {
-        this.destroy();
-    });
-
-    this.destroyDeferred = true;
-};
```
Comment (dnahodil) [inline web-app/js/portal/prototypes/OpenLayers.js]: Nice work getting rid of the unused code, too.

**Comment by dnahodil** [comment]
This looks good, @pmbohm. It'll need a rebase because of some of @jkburges' recent changes.
