### PR TITLE
Adjusted timezone 

### LINKED ISSUE #2332: GoGoDuck status page showing not in Australian time Zone?
Seeing in Prod and Systest

Steps to reproduce:

Create a small gogoduck job on status page look at time commenced.

What should happen:

It's in Australian time

What does happen:

It's showing as some other timezone

ie 1249pm Australian time job started shows as 2:49am on status page

This has only changed since I completed testing because I spoke to @anguss00 last Friday (16/09/2016) about a csv point job that I started at 817 and was still going at 10am and know I saw 0817 on the status page

### PR DESCRIPTION
**Pull request by bhasin85**
Fixes #2332

### CODE REVIEW

File: grails-app/controllers/au/org/emii/portal/WpsController.groovy [hunk 1]
```diff
@@ -63,7 +64,7 @@ class WpsController extends HostVerifyingController {
                 job: [
                     uuid: params.uuid,
                     reportUrl: g.createLink(action: 'jobReport', absolute: true, params: params),
-                    createdTimestamp: new DateTime(String.valueOf(execResponse.Status.@creationTime)),
+                    createdTimestamp: new DateTime(String.valueOf(execResponse.Status.@creationTime)).withZone( DateTimeZone.forID( "Australia/Melbourne" )),
```
Comment (julian1) [inline grails-app/controllers/au/org/emii/portal/WpsController.groovy]: hard-coding the timezone doesn't seem right to me. wouldn't this be a problem for niwa if their using the portal?

Comment (bhasin85) [inline grails-app/controllers/au/org/emii/portal/WpsController.groovy]: @julian1  I agree it will be a problem. I have moved the timezone to the config file. :+1:

Comment (julian1) [inline grails-app/controllers/au/org/emii/portal/WpsController.groovy]: What happens if a portal-end user is outside australia/melbourne? will setting the timezone explicitly change any display behavior on the client side?

Comment (julian1) [inline grails-app/controllers/au/org/emii/portal/WpsController.groovy]: The server shouldn't be hard-coding the timezone for the client. In the past we always invested the effort to fix time/zone formatting issues - and without resorting to coding the behavior on the server. So there is already a precedent in terms of effort that's been invested in avoiding this kind of change. @jonescc any thoughts?

Comment (julian1) [inline grails-app/controllers/au/org/emii/portal/WpsController.groovy]: Just to note, javascript dateTimes native-representation is utc/zulu time. So, if the server always sends UTC, the client only needs to use toLocaleString() or similar to apply the client's locale to extract the correct timezone formatted value.
```
d = new Date()
Date 2016-10-13T23:21:57.532Z
d.toUTCString()
"Thu, 13 Oct 2016 23:21:57 GMT"
d.toLocaleString()
"14/10/2016, 10:21:57 am"
```

**Comment by julian1** [comment]
Hi, what happens if the client is in WA, or SA or NT, or NZ, or anywhere outside NSW DST?

**Comment by bhasin85** [comment]
@julian1  I have updated the logic to retrieve the Timezone from the browser and pass it to the server.

**Comment by julian1** [comment]
@bhasin85 are you sure this is necessary? I don't understand why the server can't just send the time in UTC format. Then when it's displayed on the client you just call toLocalDateTime() in js to format it correctly according to the timezone of the user.

**Comment by bhasin85** [comment]
@julian1  Please review the changes.
