### PR TITLE
Fixes #2249 date range logic validation

### LINKED ISSUE #2249: Gridded collection date field does not turn red or popup open indicating wrong date format
App version: 4.25.1
            Build date: Wed Jul 27 11:13:05 AEST 2016
            Build number: 64
            Git ref: 49f8cf51f40bb01dbe7043ccbad276aa47b0ac25

Steps to reproduce:

Add any gridded collection such as radar or satellite

On step 2 click in from date field and manually type a date using hyphens - instead of forward slash / 

Proceed to step 3 and check dates

What should happen:
On step 2 box around the date field used to go red and also a popup would open indicating format should be in YYYY/MM/DD

What does happen:

No notification but the date is not applied on step 3

### PR DESCRIPTION
**Pull request by pmbohm**
Upgrade Moment.js

### CODE REVIEW

**Comment by pmbohm** [comment]
Fixes #2285

File: web-app/js/portal/details/NcWmsPanel.js [hunk 1]
```diff
@@ -232,17 +234,44 @@ Portal.details.NcWmsPanel = Ext.extend(Ext.Container, {
...
+            if (datePicker.pickerType == this.START_DATE) {
+                start = date;
+            }
+            else {
+                end = date;
+            }
+
+            if (start.isValid() && end.isValid() && !this._isDateRangeValid(start,end)) {
+                return String.format(OpenLayers.i18n('dateFormLogicalError'),
+                    start.format('Do MMMM YYYY'),
```
Comment (anguss00) [inline web-app/js/portal/details/NcWmsPanel.js]: Are these the errors that will appear for the user?

Comment (anguss00) [inline web-app/js/portal/details/NcWmsPanel.js]: Don't mind me, all good!
