### PR TITLE
Viewport Step 123 navigation buttons - no action when selected card already active

### LINKED ISSUE #1962: Access to Step 2 and 3 without selecting data collection
**Steps to reproduce**
* Go to step 1 of the Portal - don't select any data collections
* Click on the Step 1 tab
* Click on Step 2 or Step 3 tabs

**What does happen**
You can access steps 2 and 3 with no data collections selected

**What should happen**
You shouldn't be able to access steps 2 and 3 until you have selected a data collection

### PR DESCRIPTION
**Pull request by pmbohm**
Fixes #1962

### CODE REVIEW

File: web-app/js/portal/ui/NavigableCardLayout.js [hunk 1]
```diff
@@ -27,10 +27,11 @@ Portal.ui.NavigableCardLayout = Ext.extend(Ext.layout.CardLayout, {
     },
 
     setActiveTab: function(tabIndex) {
-        this.setActiveItem(tabIndex);
-
-        this.container._highlightActiveTab();
-        this.container.fireEvent('tabchange', this.container);
+        if (tabIndex  !=  this.getActiveItemIndex()) {
```
Comment (danfruehauf) [inline web-app/js/portal/ui/NavigableCardLayout.js]: Double spaces in this line.

**Comment by pmbohm** [comment]
@danfruehauf New code tidied code pushed
